name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip3 install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint */*.py | grep rated > docs/pylint_score_line.txt
        python3 .github/workflows/pylint_score.py